FirstApp/Models/ErrorViewModel.cs
namespace FirstApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

FirstApp/Models/Student.cs
namespace FirstApp.Models
{
    public class Student
    {
        public int StudentId { get; set; }
        public string StudentName { get; set; }
        public int StudentAge { get; set; }
    }
}

FirstApp/Controllers/BookController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace FirstApp.Controllers
{
    public class BookController : Controller
    {
        // GET: BookController
        public ActionResult Index()
        {
            return View();
        }

        // GET: BookController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: BookController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: BookController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: BookController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: BookController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: BookController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: BookController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

FirstApp/Controllers/EmployeeController.cs
using Microsoft.AspNetCore.Mvc;

namespace FirstApp.Controllers
{
    public class EmployeeController : Controller
    {
        public IActionResult Index()
        {
            return View("Index");
            // return View("SharedView");
        }

        public IActionResult GetEmp()
        {
            return View();
        }
    }
}

FirstApp/Controllers/HomeController.cs
using FirstApp.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace FirstApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

       

        private IConfiguration settings;

        public HomeController (IConfiguration configuration)
        {
            settings = configuration;
        }
        public string MyIndex()
        {
            string con = settings.GetConnectionString("DefaultConnection");
                //Convert.ToString(settings["ConnectionStrings:DefaultConnection"]);
            return "Jai shree Ram !!!  bharat mata ki Jai  "+con;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult RedirectExample()
        {
            return Redirect("/Home/Index");
        }

        public IActionResult GetJsonData()
        {
            var data = new { Name="Kashi",Age= 27};
            return Json(data);
        }

        public IActionResult GetHtmlText()
        {
            return Content("<h1>Hello World !</h1>","text/HTML");
        }

        public IActionResult BadRequestExample()
        {
            return BadRequest();
        }

        public IActionResult NotFoundExample()
        {
            return NotFound();
        }

        public IActionResult GetPartialView()
        {
            return PartialView("_PartialView");
        }

       // public IActionResult DownloadFile()
        //{
          //  var fileBytes = GetFileBytes();
           // return File(FileBytes,"Application/pdf","myfile.pdf");
       // }
    }
}

FirstApp/Controllers/StudentController.cs
using Microsoft.AspNetCore.Mvc;

namespace FirstApp.Controllers
{
    public class StudentController : Controller
    {
        public IActionResult GetInfo()
        {
            return View();
        }

        [HttpPost]
        public IActionResult GetInfo(string name,string sex)
        {
            return View();
        }

        public IActionResult DisplayResult()
        {
            return View();
        }

        public IActionResult Index()
        {
            return View();
           // return View("SharedView");
        }

        //[ActionName("Welcome")]
        //public string Index()
        //{
            //return "Hello Kashi";
        //}

        [NonAction]
        public string NoAction()
        {
            return "Captain America";
        }

        [HttpGet]
        public string HttpGetAction()
        {
            return "In Get";
        }

        [HttpPost]
        public string HttpPostAction()
        {
            return "In Post";
        }

        [HttpPut]
        public string HttpPutAction()
        {
            return "In Put";
        }

        [HttpDelete]
        public string HttpDeleteAction()
        {
            return "In Delete";
        }

        [HttpHead]
        public string HttpHeadAction()
        {
            return "In Head";
        }

        [HttpPatch]
        public string HttpPatchAction()
        {
            return "In Patch";
        }

        [HttpOptions]
        public string HttpOptionsAction()
        {
            return "In Options";
        }
    }
}

FirstApp/Views/Employee/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h1>Elon Musk</h1>
@await Html.PartialAsync("MyPartialView")
@{
    Html.RenderPartial("MyPartialView");
}

FirstApp/Views/Employee/getEmp.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h1>Get the Employee</h1>

FirstApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

FirstApp/Views/Shared/MyPartialView.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h1>
    this is my partial view , Hi from Partial view !!!!
</h1>

FirstApp/Views/Shared/SharedView.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h1>
    This is common welcome for Emp and Student
</h1>

FirstApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FirstApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FirstApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FirstApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="Index">Student</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="Index">Emp</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - FirstApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

FirstApp/Views/Student/DisplayResult.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h1>display results: DeadPool</h1>

FirstApp/Views/Student/GetInfo.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h1>Student's' Portal</h1>
@Html.Partial("MyPartialView")
<form asp-controller="Student" asp-action="GetInfo" method="post">
    <div class="form-group">
        <label>Name:</label>
        <input class="form-control" name="name" />
    </div>
    <div class="form-group">
        <label>Sex:</label>
        <select class="form-control" name="name">

        <option value="M">Male</option>
        <option value="F">Female</option>
        </select>

    </div>
    <div class="m-1">
        <button class="btn btn-primary" type="submit">Submit</button>
    </div>
</form>

FirstApp/Views/Student/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h1>Welcome Kashi</h1>
@Html.Partial("MyPartialView")
<a asp-controller="Student" asp-action="GetInfo">Get Info</a>
@{
    await Html.RenderPartialAsync("MyPArtialView");
}